title = "Franco Pasut"
baseURL = "https://francopasut.netlify.app/"
theme = ["ananke"]
resourceDir = "../resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

ignoreLogs = ['warning-goldmark-raw-html']

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 6 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = "Franco Pasut  Web Site"
# languageDirection = 'rtl' for Right-To-Left languages

[languages.it]
contentDir = "content/it"
languageCode = 'it-IT'
weight = 2
title = "Sito Web di Franco Pasut"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-blue"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
# featured_image_claAnanke Frss = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 6
custom_css = ["custom.css"]

# [params.ananke.social.share]
# networks = [
#   "email"
# ]

# [params.ananke.social.follow]
# networks = [
  
# ]

# [params.ananke.social.facebook]
# username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

# [params.ananke.social.linkedin]
# username = "patrickkollitsch"

# [params.ananke.social.bluesky]
# username = "kollitsch.dev"
